SELECT * FROM MEMBER;

DESC MEMBER;

INSERT INTO MEMBER(ID, PW, NAME, GENDER, AGE, ROLE)
VALUES('admin01', 'admin01', '관리자1', 'F', 20, 'MANAGER');

COMMIT;

SELECT * FROM REPORT;
DESC REPORT;
DESC EMPLOY;

INSERT INTO REPORT 
VALUES(SEQ_REPORT_NO.NEXTVAL, SYSDATE, 'N', SYSDATE, '내용', 'user02');

COMMIT;